Improved filelock, and more appropriate variable names.

diff --git a/contrib/dmenu/passmenu b/contrib/dmenu/passmenu
--- a/contrib/dmenu/passmenu
+++ b/contrib/dmenu/passmenu
@@ -17,50 +17,52 @@ prefix="${PASSWORD_STORE_DIR:-$HOME/.password-store}"
 password_files=( "$prefix"/**/*.gpg )
 password_files=( "${password_files[@]#"$prefix"/}" )
 password_files=( "${password_files[@]%.gpg}" )
+password=( ${password:-""} )
+before=( "${before:-}" )
+userID="$(id -u $(whoami))"
+stalelock=( "${stalelock:-""}" )
+stalelock=( "$(find '/tmp' -maxdepth 1 -name "passmenulock."$userID".*" -user $(whoami) -print0  -quit)" ) &&
+cleanup=True || { true; cleanup=False; }
 
 _finish () {
   [[ -n $before ]] &&
-  printf "$before" | xclip -sel "$X_SELECTION" -i
-  [[ True = "$remove" ]] &&
-  if compgen -G "/tmp/passmenu.1000*" >/dev/null 2>&1 ;then
-    rmdir /tmp/passmenu."$uid".* >/dev/null 2>&1
+  printf "$before" | base64 -d | xclip -sel "$X_SELECTION" -i
+  [[ True = "$cleanup" ]] &&
+  if compgen -G "/tmp/passmenulock.1000*" >/dev/null 2>&1 ;then
+    rmdir /tmp/passmenulock."$userID".* >/dev/null 2>&1
   fi
   exit
 }
 trap _finish EXIT
 
 ## Clearing stale Xclip loops avoids a posible race condition.
-uid="$(id -u $(whoami))"
-remove=False
-if compgen -G "/tmp/passmenu.1000*" >/dev/null 2>&1 ;then
-  stale="$(find /tmp/passmenu."$uid".* -print -quit | 
-  sed -e "s/\/tmp\/passmenu\.[0-9]\{1,6\}\?\..*\.//g")"
-  report="$(ps -u $(id -u $(whoami)) aux | grep "bash" | 
-  grep "passmenu" | grep -v "$$")"
-  if [[ "$report" == *"$stale"* ]] ;then 
-    kill "$stale" && rmdir /tmp/passmenu.$uid.* >/dev/null 2>&1 || exit 1
+if test -n "$stalelock" ;then
+  report=( "$(ps -u $(id -u $(whoami)) aux | grep "bash" | 
+  grep "passmenu" | grep -v "$$")" )
+  stalePID=( "$(printf $stalelock | 
+  sed -e "s/\/tmp\/passmenulock\.[0-9]\{1,6\}\?\..*\.//g")" )
+  if [[ "$report" == *"$stalePID"* ]] ;then
+    kill "$stalePID" || exit 1
   else
-    rmdir /tmp/passmenu.$uid.* >/dev/null 2>&1 || exit 1
+    rmdir /tmp/passmenulock.$userID.* >/dev/null 2>&1 || exit 1
   fi
 fi
 
 ## dmenu exits on KeyPress not KeyRelease.
-## It would be nice to send KeyRelease event to some dummy window.
-## psydocode: xdotool getwindowfocus; create dummy window;
-## exec dmenu; close dummy window; restore focus.
-password=${password:-}
+# It would be nice to send KeyRelease event to some dummy window.
+# psydocode: xdotool getwindowfocus; create dummy window;
+# exec dmenu; close dummy window; restore focus.
 for password in $(printf '%s\n' "${password_files[@]}" | dmenu -f "$@"); do
   passel+=("$password")
 done
 
-before=${before:-}
 [[ -n $password ]] || exit
-before="$(xclip -sel "$X_SELECTION" -o >/dev/null 2>&1)" || true
+# It would be nice to first somehow test if string exists.
+before="$(xclip -sel "$X_SELECTION" -o 2>/dev/null | base64)" || true
 
 umask 077
-mktemp -d "/tmp/passmenu."$uid".XXXXXXXXXX"."$$" >/dev/null 2>&1 ||
-{ echo >&2 ":: Unable to make a filelock."; exit 1; }
-remove=True
+( mktemp -d "/tmp/passmenulock."$userID".XXXXXXXXXX"."$$" >/dev/null 2>&1 && cleanup=True ||
+  { echo >&2 ":: Unable to make a filelock."; exit 1; } )
 
 if [[ $typeit -eq 0 ]]; then
   if [ ${#passel[@]} -gt "1" ]; then
