Added --notify feature using libnotify.

diff --git a/contrib/dmenu/passmenu b/contrib/dmenu/passmenu
--- a/contrib/dmenu/passmenu
+++ b/contrib/dmenu/passmenu
@@ -3,10 +3,17 @@
 shopt -s nullglob globstar failglob
 set -euo pipefail
 
-tool=${1:-} 
+arg1=${1:-} 
+arg2=${2:-} 
 typeit=0
-if [[ $tool == "--type" ]]; then
-  typeit=1
+notifyit=0
+
+if [[ '--type' == "$arg1" ]] || [[ '--type' == "$arg2" ]]; then
+  typeit=1;
+  shift
+fi 
+if [[ '--notify' == "$arg1" ]] || [[ '--notify' == "$arg2" ]]; then
+  notifyit=1;
   shift
 fi
 
@@ -21,6 +28,7 @@ password=( '' )
 cleanup=( '' )
 before=( '' )
 userID=( "$(id -u $(whoami))" )
+PROGRAM="${0##*/}"
 
 _finish () {
   [[ True == $cleanup ]] &&
@@ -32,6 +40,19 @@ _finish () {
   exit
 }
 
+_notify () {
+  message=$1
+  [[ "$notifyit" == 1 ]] && 
+  notify-send "$message" --icon=dialog-information || 
+  printf '%s\n' "$message"
+}
+
+( [[ "$notifyit" == 1 ]] & hash notify-send 2>/dev/null || 
+  { printf '%s\n' "e: cannot find libnotify."; exit 1; }
+[[ "$typeit" == 1 ]] & hash xdotool 2>/dev/null || 
+  { _notify "e: cannot find xdotool."; exit 1; } )
+
+
 ## dmenu exits on KeyPress not KeyRelease.
 # It might be nice to send KeyRelease event to some dummy window.
 # psydocode: xdotool getwindowfocus; create dummy window;
@@ -42,6 +63,7 @@ done
 
 [[ -n $password ]] || exit
 
+# Runs the _finish funtion on exit. 
 trap _finish EXIT
 
 ## Clearing old filelock(s). 
@@ -58,47 +80,49 @@ if test -n "$stalelock" ;then
     kill "$stalePID" || exit 1
   else
     rmdir /tmp/passmenu."$userID".* >/dev/null 2>&1 ||
-    { echo ":: Unable to clear old filelock"; exit 1; }
+    { _notify ":: Unable to clear old filelock"; exit 1; }
   fi
 fi
 
 ## Adding a new filelock
 ( mktemp -d "/tmp/passmenu."$userID".XXXXXXXXXX"."$$".lock >/dev/null 2>&1 && cleanup=True ||
-  { echo >&2 ":: Unable to make a filelock."; exit 1; } )
+  { _notify ":: Unable to make filelock."; exit 1; } )
 
 cleanup=True
 # It would be nice to first first test if string exists.
 before="$(xclip -sel "$X_SELECTION" -o 2>/dev/null | base64)" || true
 
 if [[ $typeit -eq 0 ]]; then
+  ## CLIPBOARD
   if [ ${#passel[@]} -gt "1" ]; then
     round=0
     for entry in "${passel[@]}"; do
-      printf '%s\n' "Sending "${passel[$round]}" via "$X_SELECTION""
       pass show "$entry" | sed '1!d' | tr -d '\n' |
       xclip -l 1 -quiet -sel "$X_SELECTION" >/dev/null 2>&1
+      _notify "Sent "${passel[$round]}" via "$X_SELECTION""
       round=`expr $round + 1`
     done
   else
-    printf '%s\n' "Sending "$password" via "$X_SELECTION""
     pass show "$password" | sed '1!d' | tr -d '\n' |
-    xclip -sel "$X_SELECTION" -i && sleep "$CLIP_TIME" 
+    xclip -sel "$X_SELECTION" -i
+    _notify "Sent "$password" via "$X_SELECTION""
+    sleep "$CLIP_TIME"
   fi
 else
-  command -v xdotool >/dev/null 2>&1 || 
-  { echo >&2 "e: cannot find xdotool."; exit 1; }
+  ## TYPE
   if [ ${#passel[@]} -gt "1" ]; then
     round=0
     for entry in "${passel[@]}"; do
-      printf '%s\n' "Sending "${passel[$round]}" via "$X_SELECTION""
       printf '' | xclip -l 1 -quiet -sel "$X_SELECTION" >/dev/null 2>&1
       pass show "$entry" | sed '1!d' | tr -d '\n' | 
-      xdotool type --clearmodifiers --file -
+      xdotool type --delay --clearmodifiers --file -
+      _notify "Sent "${passel[$round]}" via "autotype""
       round=`expr $round + 1`
     done
   else
     pass show "$password" | sed '1!d' | tr -d '\n' |
-    xdotool type --clearmodifiers --file -
+    xdotool type --delay --clearmodifiers --file -
+    _notify "Sent "$password" via "autotype""
   fi
 fi
 exit
